### ISSUE TITLE
May you should use StringComparer.InvariantCultureIgnoreCase

### ISSUE THREAD

**Issue by X509Whatever** [AntonioMGit/CalculatorService#3]
https://github.com/AntonioMGit/CalculatorService/blob/054874b3f301cc11e373880da26e881245c9d23c/CalculatorClient/Client.cs#L24

**Comment by AntonioMGit** [comment]
StringComparison.InvariantCultureIgnoreCase added in if conditions.
![image](https://user-images.githubusercontent.com/98851694/160636543-20b5cdc5-a478-4022-85c6-fb97112c1efc.png)
