### ISSUE TITLE
Using += here is not worth

### ISSUE THREAD

**Issue by X509Whatever** [AntonioMGit/CalculatorService#4]
https://github.com/AntonioMGit/CalculatorService/blob/054874b3f301cc11e373880da26e881245c9d23c/CalculatorClient/Client.cs#L33

Btw, += is not resolved on compilation.

![image](https://user-images.githubusercontent.com/49149147/160435706-f2c91a6f-d4f0-4ed6-8f1c-e26ab3272c5e.png)

_More IL too, but this the easiest way to explain._

**Comment by AntonioMGit** [comment]
String changed.
![image](https://user-images.githubusercontent.com/98851694/160636989-213e8db1-23fd-440a-8c40-9cc7c5b36a33.png)
