### ISSUE TITLE
May you want to call the param path instead of url (as it's no the url)

### ISSUE THREAD

**Issue by X509Whatever** [AntonioMGit/CalculatorService#5]
https://github.com/AntonioMGit/CalculatorService/blob/054874b3f301cc11e373880da26e881245c9d23c/CalculatorClient/Client.cs#L155

Same for another vars.. may you should take a look and use english/rename them properly.

**Comment by AntonioMGit** [comment]
Name changed in this variable and others.
![image](https://user-images.githubusercontent.com/98851694/160637391-98dc5d63-b862-45f9-9f19-e038e294afda.png)
