### ISSUE TITLE
Why not calling once the write method with just only one single string ie. using \n

### ISSUE THREAD

**Issue by X509Whatever** [AntonioMGit/CalculatorService#6]
https://github.com/AntonioMGit/CalculatorService/blob/054874b3f301cc11e373880da26e881245c9d23c/CalculatorClient/Client.cs#L178-L179

**Comment by AntonioMGit** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/98851694/160637688-96379516-3b8c-4a34-a5b7-f7a8f63cc0d4.png)
