### ISSUE TITLE
Iface should be called IOperation instead of IOperations.

### ISSUE THREAD

**Issue by X509Whatever** [AntonioMGit/CalculatorService#7]
https://github.com/AntonioMGit/CalculatorService/blob/054874b3f301cc11e373880da26e881245c9d23c/CalculatorClient/Client.cs#L141

Additionally, the method DoOperations has a bad name too (are you doing one operation.. or many of them in order to use plural?)

**Comment by AntonioMGit** [comment]
Name changed.
